### PR TITLE
General fixes

### PR DESCRIPTION
**Pull request by developer9998**
- Fix method for unpatching
- Fix not being able to connect to Photon servers

### CODE REVIEW

**Comment by RusJJ** [comment]
Merged manually. Forgot about it, lol. Thanks!

**Comment by ghost** [comment]
Does this work for the latest update if anyone tested it?

**Comment by RusJJ** [comment]
No

**Comment by ghost** [comment]
Alright

**Comment by developer9998** [comment]
is it silly

**Pull request closed without merging**
